version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_bata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exchang
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  app:
      image: app
      depends_on: db
      ports:
        - 8080:8080
      restart: always
